spring:
    application:
        name: oauth2-auth-server
    devtools:
        livereload:
            port: 35781
    h2:
        console:
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        open-in-view: false
server:
    port: 8081
    servlet:
        context-path: /auth-server
